# NOTICE - this deployment contains code modified from the Bitnami Postgres Helm Chart so that 
# the Labels logic can be synchronized. Please see licenses/BITNAMI_LICENSE.md for the related
# license
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "janeway.fullname" . }}-nginx
  namespace: {{ .Release.Namespace }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.commonLabels ) "context" . ) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
    {{ include "common.labels.component.other" . }}
  {{ if .Values.commonAnnotations -}}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  nginx.conf: |
{{- .Values.primary.nginx.config | nindent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "janeway.fullname" . }}-nginx-start
  namespace: {{ .Release.Namespace }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.commonLabels ) "context" . ) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
    {{ include "common.labels.component.other" . }}
  {{ if .Values.commonAnnotations -}}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  wait-for-janeway.sh: |
    until [ -S /tmp/janeway.sock ]; do
      echo "Nginx is waiting for Janeway to be ready..."
      sleep 3
    done
    echo "Janeway is ready."
    exec nginx -g "daemon off;"