# Allows traffic between ALL Janeway pods explicitly. Use if
# needed in your environment.
{{- if .Values.networkPolicy.allowInterpodTraffic }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "janeway.fullname" . }}-all-inter
  namespace: {{ .Release.Namespace }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.commonLabels ) "context" . ) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
    {{ include "common.labels.component.app" . }}
  {{ if .Values.commonAnnotations -}}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

---

# Allow ingress (incoming) external HTTP traffic to janeway pod
{{ if .Values.networkPolicy.allowIngress -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "janeway.fullname" . }}-http
  namespace: {{ .Release.Namespace }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.commonLabels ) "context" . ) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
    {{ include "common.labels.component.app" . }}
  {{ if .Values.commonAnnotations -}}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.commonLabels ) "context" . ) }}
    matchLabels:
      {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      {{ include "common.labels.component.app" . }}
  policyTypes:
  - Ingress
  ingress:
  - from: []
    ports:
      - port: 8000 # The port of the Nginx container on the pod.
{{- end }}

---

# Explicitly allow external access to SMTP server
{{ if .Values.networkPolicy.allowSMTPEgress -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "janeway.fullname" . }}-smtp
  namespace: {{ .Release.Namespace }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.commonLabels ) "context" . ) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
    {{ include "common.labels.component.app" . }}
  {{ if .Values.commonAnnotations -}}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.commonLabels ) "context" . ) }}
    matchLabels:
      {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      {{ include "common.labels.component.app" . }}
  policyTypes:
  - Egress
  egress:
  - to: []
    ports:
      - port: 25
{{- end }}