name: Publish Helm Chart

on:
  release:
    types: [published] # Release and Pre-Release
  
jobs:
  Publish-Helm-Chart:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - uses: azure/setup-helm@v5
        with:
          version: 'latest' # default is latest (stable)
        id: install

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Chart
        shell: bash
        run: helm package .

      - name: Push Chart to GHCR
        shell: bash
        run: helm push *.tgz oci://ghcr.io/usmai-library-consortium/janeway